# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2.1.4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-build-x-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-x-
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: ./app
        file: ./app/Dockerfile  
        push: false
        load: true
        tags: oittaa/avif-converter:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
    - name: Docker container up
      run: docker run -d --rm -p 8080:8080 --env PORT=8080 --name avif-converter oittaa/avif-converter
    - name: Wait 10 seconds
      run: sleep 10
    - name: Check running containers
      run: docker ps -a
    - name: Check the container web page reachability
      run: curl --output /dev/null -s --retry 10 --retry-connrefused http://localhost:8080/
    - name: Check the container API reachability
      run: curl --output /dev/null -s -L -F "file=@test_images/test.png" http://localhost:8080/api
    - name: Check Docker logs
      run: docker logs avif-converter
    - name: Docker container down
      run: docker stop avif-converter
